### ISSUE TITLE
Long lines become unreadable

### ISSUE THREAD

**Issue by andrewjtam** [akira-cn/code-to-image#1]
When entering longer lines, the text wraps over itself and becomes unreadable.

The line i put in was:
"realmConfig = new RealmConfiguration.Builder(getActivity()).deleteRealmIfMigrationNeeded().build();"

**Comment by akira-cn** [comment]
There is a bug when line break on html2canvas-0.5.0-beta3. So I disabled the word break. Thanks~

**Comment by akira-cn** [comment]
I downgraded html2canvas from 0.5.0-alpha1 to v0.4.1 because of that a wide line without break-word will cause a very wide image that difficult to read on mobile phone.
